### ISSUE TITLE
Look for alternatives to bintray

### ISSUE THREAD

**Issue by labra** [weso/shex-s#185]
We are currently publishing the binaries in Bintray but it seems the service will be [no longer available after 1st May](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

Help or comments are greatly appreciated.

**Comment by thewillyhuman** [comment]
Maybe [GitHub](https://github.com/features/packages) package registry fits our need.

**Comment by labra** [comment]
We are publishing now at github packages as suggedted by @thewillyhuman
